version: '3.8'
services:
  couchbase:
    image: "couchbase"
    # not sure which port couchbase uses
    ports:
     - "8091:8091"
  backend:
    build: ./backend/
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - couchbase
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
