version: "3.8"
services:
    couchbase:
        image: couchbase/server
        # not sure which port couchbase uses
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
    backend:
        build: ./backend/
        env_file:
            - ./backend/.env
        ports:
            - 5000:5000
        volumes:
            - ./backend/src:/usr/src/app/src
        depends_on:
            - couchbase
