version: "3.8"
services:
    couchbase:
        platform: linux/x86_64
        image: couchbase/server:6.6.5
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
    backend:
        build: ./backend/
        env_file:
            - ./backend/.env
        ports:
            - 10001:10001
        volumes:
            - ./backend/src:/usr/src/app/src
        depends_on:
            - couchbase
